language: python
sudo: false
python:
- 2.7
rvm:
  - 2.2.0
addons:
  apt:
    packages:
    - python-lxml
    - python-pip
    
before_script:
- composer self-update -q
- if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}
install:
- gem install kramdown-rfc2629
- pip install xml2rfc
- deactivate
- rvm install 2.2.0
- rvm use 2.2.0
- ruby --version
- gem install rake
- gem install cddl
script: 
- xml2rfc draft-ietf-cose-msg.xml -o cose.xml --exp
- rake verify
- make ghpages
